#!/bin/bash

# Script de commandes SSH pour diagnostiquer et corriger les problèmes sur le serveur
echo "🔧 COMMANDES POUR DIAGNOSTIC SUR LE SERVEUR (root@82.25.116.122)"
echo "================================================================"
echo ""
echo "Copiez et exécutez ces commandes sur votre serveur SSH :"
echo ""

echo "# 1. Vérifier les services Supabase en cours d'exécution"
echo "echo '🔍 Services Supabase actifs :'"
echo "ps aux | grep -E '(supabase|kong|postgres)' | grep -v grep"
echo ""

echo "# 2. Vérifier la configuration Nginx"
echo "echo '📋 Configuration Nginx pour ges-cab.com :'"
echo "cat /etc/nginx/sites-available/ges-cab* | head -30"
echo ""

echo "# 3. Vérifier les logs Nginx"
echo "echo '📜 Dernières erreurs Nginx :'"
echo "tail -20 /var/log/nginx/error.log"
echo ""

echo "# 4. Tester les ports locaux"
echo "echo '🌐 Ports en écoute :'"
echo "netstat -tlnp | grep -E ':(80|443|8000|54321|54323)'"
echo ""

echo "# 5. Vérifier le statut des services"
echo "echo '⚙️ Statut des services :'"
echo "systemctl status nginx"
echo "systemctl status supabase-* 2>/dev/null || echo 'Services Supabase personnalisés non trouvés'"
echo ""

echo "# 6. Test local des services"
echo "echo '🧪 Test local des services :'"
echo "curl -s http://localhost:3000/ | head -5 || echo 'Frontend local non accessible'"
echo "curl -s http://localhost:54323/ | head -5 || echo 'Studio local non accessible'"
echo "curl -s http://localhost:54321/rest/v1/ || echo 'API locale non accessible'"
echo ""

echo "# 7. Correction potentielle du problème d'authentification"
echo "echo '🔧 Correction des problèmes identifiés :'"
echo ""
echo "# Désactiver l'authentification Basic Auth Kong (si activée)"
echo "# Vérifier le fichier de configuration Kong"
echo "find /etc -name '*kong*' -type f 2>/dev/null | head -5"
echo ""

echo "# 8. Redémarrer les services si nécessaire"
echo "echo '🔄 Redémarrage des services :'"
echo "# sudo systemctl restart nginx"
echo "# sudo docker-compose restart  # Si utilisation de Docker"
echo "# sudo systemctl restart supabase-*  # Si services systemd"
echo ""

echo "=========================================="
echo "💡 ANALYSE RAPIDE BASÉE SUR LE DIAGNOSTIC"
echo "=========================================="
echo ""
echo "✅ POINTS POSITIFS :"
echo "  • DNS fonctionne parfaitement"
echo "  • Certificats SSL valides"
echo "  • API Supabase répond (même si 401)"
echo "  • Performance excellente"
echo ""
echo "⚠️ PROBLÈMES IDENTIFIÉS :"
echo "  • Frontend : Authentification Basic Auth activée (WWW-Authenticate: Basic realm=\"kong\")"
echo "  • Studio : Service non démarré (502 Bad Gateway)"
echo "  • CORS : Headers manquants"
echo ""
echo "🎯 SOLUTION PRIORITAIRE :"
echo "  1. Désactiver l'auth Kong sur le frontend"
echo "  2. Démarrer le service Studio Supabase"
echo "  3. Configurer les headers CORS dans Nginx"
echo ""
echo "Votre infrastructure est à 80% fonctionnelle ! 🚀"
echo "Seuls quelques ajustements sont nécessaires."