#!/bin/bash

echo "🎯 GUIDE ULTRA-SIMPLE - Configuration DNS"
echo "=========================================="
echo ""
echo "📋 SITUATION ACTUELLE :"
echo "   ges-cab.com     → 84.32.84.32 ❌ (Hostinger parking)"
echo "   www.ges-cab.com → 84.32.84.32 ❌ (Hostinger parking)"
echo "   api.ges-cab.com → 82.25.116.122 ✅ (Déjà bon !)"
echo "   studio.ges-cab.com → 82.25.116.122 ✅ (Déjà bon !)"
echo ""
echo "🎯 OBJECTIF : Changer les 2 premiers vers 82.25.116.122"
echo ""
echo "=============================================="
echo ""

read -p "🔑 Avez-vous accès à votre compte Hostinger ? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo "🚀 PARFAIT ! Suivez ces 7 étapes simples :"
    echo ""
    echo "1️⃣  Allez sur : https://hpanel.hostinger.com"
    echo "2️⃣  Connectez-vous avec votre email/mot de passe"
    echo "3️⃣  Cliquez sur 'Domaines' dans le menu"
    echo "4️⃣  Cliquez sur 'ges-cab.com'"
    echo "5️⃣  Cherchez 'DNS Zone Editor' et cliquez dessus"
    echo "6️⃣  Trouvez les lignes avec '84.32.84.32' et remplacez par '82.25.116.122'"
    echo "7️⃣  Cliquez 'Save' ou 'Enregistrer'"
    echo ""
    echo "⏰ Puis lancez la surveillance :"
    echo "   ./monitor-dns-propagation.sh"
    echo ""
else
    echo ""
    echo "🆘 PAS D'ACCÈS ? Options :"
    echo ""
    echo "📞 Support Hostinger :"
    echo "   • Chat : https://hpanel.hostinger.com (coin bas-droite)"
    echo "   • Email : support@hostinger.com"
    echo "   • Téléphone : voir leur site web"
    echo ""
    echo "💬 Dites-leur exactement :"
    echo "   'Je veux changer les DNS A de ges-cab.com et www.ges-cab.com"
    echo "    de 84.32.84.32 vers 82.25.116.122'"
    echo ""
fi

echo "=============================================="
echo ""
echo "📱 Vérification rapide quand c'est fait :"
echo "   ./check-dns-status.sh"
echo ""
echo "🎉 Résultat final attendu :"
echo "   https://www.ges-cab.com → Votre application !"
echo ""