import React, { useState, useEffect, useMemo } from 'react';
import PropTypes from 'prop-types';
import { motion } from 'framer-motion';
import { X, User, FileText, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { numberToWords } from '@/lib/numberToWords';

const formatCurrency = (value) => {
  if (value === '' || value === null || value === undefined) return '';
  const num = Number(value);
  if (isNaN(num)) return '0';
  return new Intl.NumberFormat('fr-FR').format(num);
};

const parseCurrency = (value) => {
  if (typeof value !== 'string') return 0;
  const number = Number(value.replace(/\s/g, '').replace(/\D/g, ""));
  return isNaN(number) ? 0 : number;
};

const getPaymentMethodLabel = (method) => {
  switch (method) {
    case 'virement':
      return 'Virement bancaire';
    case 'cheque':
      return 'Chèque';
    case 'cartebancaire':
      return 'Carte bancaire';
    case 'especes':
      return 'Espèces';
    case 'autre':
      return 'Autre';
    default:
      return 'Virement bancaire';
  }
};

const InvoiceForm = ({ invoice, onSubmit, onCancel, onPrint, currentUser, existingInvoices = [] }) => {
  const [formData, setFormData] = useState({
    invoiceNumber: '',
    clientName: '',
    caseId: '',
    debours: {
      entrevue: 0,
      dossier: 0,
      plaidoirie: 0,
      huissier: 0,
      deplacement: 0,
    },
    honoraires: {
      forfait: 0,
      tauxHoraire: 0,
      base: 0,
      resultat: 0,
    },
    payment: {
      method: 'virement',
      provision: false,
      provisionAmount: 0,
    },
  });

  useEffect(() => {
    if (invoice) {
      setFormData(invoice);
    }
  }, [invoice]);

  const handleInputChange = (section, name, value) => {
    const parsedValue = parseCurrency(value);
    setFormData(prev => ({
      ...prev,
      [section]: { ...prev[section], [name]: parsedValue }
    }));
  };

  const handlePaymentChange = (e) => {
    const { name, value } = e.target;
    const isProvisionRadio = name === 'provision';

    setFormData(prev => {
        let newPaymentState = { ...prev.payment };

        if (isProvisionRadio) {
            newPaymentState.provision = value === 'true';
        } else if (name === 'provisionAmount') {
            newPaymentState[name] = parseCurrency(value);
        } else {
            newPaymentState[name] = value;
        }
        
        return { ...prev, payment: newPaymentState };
    });
  };

  const { totalDebours, totalHonoraires, totalHT, tva, totalTTC, resteAPayer } = useMemo(() => {
    const totalDebours = Object.values(formData.debours).reduce((sum, val) => sum + (Number(val) || 0), 0);
    const totalHonoraires = Object.values(formData.honoraires).reduce((sum, val) => sum + (Number(val) || 0), 0);
    const totalHT = totalDebours + totalHonoraires;
    const tva = totalHT * 0.18;
    const totalTTC = totalHT + tva;
    const resteAPayer = formData.payment.provision ? totalTTC - (Number(formData.payment.provisionAmount) || 0) : totalTTC;
    return { totalDebours, totalHonoraires, totalHT, tva, totalTTC, resteAPayer };
  }, [formData.debours, formData.honoraires, formData.payment.provision, formData.payment.provisionAmount]);

  // Fonction pour générer le numéro de facture selon le format : FACT-ANNEE-JJ-XXXXX-CLIENT
  const generateInvoiceNumber = (clientName) => {
    const now = new Date();
    const year = now.getFullYear();
    const day = String(now.getDate()).padStart(2, '0');
    
    // Extraire les 3 premières lettres du nom du client (en majuscules, sans espaces)
    const clientCode = clientName
      .trim()
      .replace(/[^A-Za-z]/g, '') // Supprimer tout ce qui n'est pas une lettre
      .substring(0, 3)
      .toUpperCase()
      .padEnd(3, 'X'); // Compléter avec des X si moins de 3 caractères
    
    // Trouver le plus grand numéro existant pour cette date
    const todayPrefix = `FACT-${year}-${day}-`;
    const todayInvoices = existingInvoices.filter(inv => 
      inv.invoiceNumber?.startsWith(todayPrefix)
    );
    
    let maxNumber = 0;
    todayInvoices.forEach(inv => {
      const match = inv.invoiceNumber.match(new RegExp(`${todayPrefix}(\\d{5})`));
      if (match) {
        const num = parseInt(match[1], 10);
        if (num > maxNumber) maxNumber = num;
      }
    });
    
    // Incrémenter le numéro
    const nextNumber = String(maxNumber + 1).padStart(5, '0');
    
    return `${todayPrefix}${nextNumber}-${clientCode}`;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    
    // Validation des champs requis
    if (!formData.clientName.trim()) {
      alert('Le nom du client est requis');
      return;
    }
    
    // Générer un numéro de facture si vide selon le format spécifié
    const autoGeneratedNumber = generateInvoiceNumber(formData.clientName);
    const finalData = {
      ...formData,
      invoiceNumber: formData.invoiceNumber.trim() || autoGeneratedNumber,
      // Inclure les totaux calculés
      totalTTC,
      totalHT,
      totalDebours,
      totalHonoraires,
      tva,
      resteAPayer
    };
    
    onSubmit(finalData);
  };

  const renderCurrencyInput = (label, name, value, onChange) => (
    <div className="flex items-center justify-between">
      <label className="text-slate-300 flex items-center print:text-black">
        <input type="checkbox" className="mr-3 h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 print:hidden" />
        {label}
      </label>
      <div className="relative w-48">
        <input
          type="text"
          name={name}
          value={formatCurrency(value)}
          onChange={onChange}
          className="w-full pl-3 pr-14 py-2 bg-slate-700/50 border border-slate-600 rounded-lg text-white text-right placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 print:bg-white print:text-black print:border-gray-300"
          placeholder="0"
        />
        <span className="absolute inset-y-0 right-3 flex items-center text-slate-400 text-sm print:text-gray-500">F CFA</span>
      </div>
    </div>
  );

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50 print:fixed print:inset-0 print:bg-white print:backdrop-blur-none print:p-0"
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="bg-slate-800 border border-slate-700 rounded-xl p-6 w-full max-w-5xl max-h-[90vh] overflow-y-auto print:bg-white print:border-none print:shadow-none print:max-h-full print:overflow-visible print:rounded-none print:p-8 print:max-w-full"
      >
        {/* En-tête avec boutons d'action - visible seulement à l'écran */}
        <div className="flex items-center justify-between mb-6 print:hidden">
          <h2 className="text-2xl font-bold text-white">
            Facture Professionnelle
          </h2>
          <div className="flex gap-2">
            <Button type="button" variant="outline" onClick={onPrint} className="border-blue-500 text-blue-400 hover:bg-blue-500/20">
              <Printer className="w-4 h-4 mr-2" />
              Imprimer
            </Button>
            <Button variant="ghost" size="icon" onClick={onCancel} className="text-slate-400 hover:text-white">
              <X className="w-5 h-5" />
            </Button>
          </div>
        </div>

        {/* En-tête de facture - visible à l'impression */}
        <div className="hidden print:block mb-8">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold text-gray-800 mb-2">FACTURE</h1>
              <div className="text-sm text-gray-600">
                <p><strong>Cabinet Juridique</strong></p>
                <p>123 Avenue de la Justice</p>
                <p>75001 Paris, France</p>
                <p>Tél: +33 1 23 45 67 89</p>
                <p>Email: contact@cabinet.fr</p>
              </div>
            </div>
            <div className="text-right">
              <div className="bg-gray-100 p-4 rounded">
                <p className="text-sm text-gray-600">N° de Facture</p>
                <p className="text-xl font-bold text-gray-800">{formData.invoiceNumber || generateInvoiceNumber(formData.clientName)}</p>
                <p className="text-sm text-gray-600 mt-2">Date: {new Date().toLocaleDateString('fr-FR')}</p>
              </div>
            </div>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Informations client - visible à l'impression */}
          <div className="hidden print:block mb-8">
            <div className="grid grid-cols-2 gap-8">
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-3">Facturer à:</h3>
                <div className="bg-gray-50 p-4 rounded border">
                  <p className="font-semibold text-gray-800">{formData.clientName || 'Nom du client'}</p>
                  <p className="text-gray-600">Adresse du client</p>
                  <p className="text-gray-600">Code postal Ville</p>
                  <p className="text-gray-600">Pays</p>
                </div>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-3">Dossier:</h3>
                <div className="bg-gray-50 p-4 rounded border">
                  <p className="text-gray-700"><strong>Référence:</strong> {formData.caseId || 'Non spécifié'}</p>
                  <p className="text-gray-700"><strong>Date limite:</strong> {new Date().toLocaleDateString('fr-FR')}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Formulaire de saisie - visible seulement à l'écran */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 print:hidden">
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2"><FileText className="w-4 h-4 inline mr-2" />N° Facture</label>
              <input type="text" name="invoiceNumber" value={formData.invoiceNumber} onChange={(e) => setFormData({...formData, invoiceNumber: e.target.value})} className="w-full px-4 py-3 bg-slate-700/50 border border-slate-600 rounded-lg text-white" placeholder="Ex: FACT-2025-07-00001-BNI" />
              {!formData.invoiceNumber && formData.clientName && (
                <p className="text-xs text-slate-400 mt-1">
                  Sera généré: {generateInvoiceNumber(formData.clientName)}
                </p>
              )}
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2"><User className="w-4 h-4 inline mr-2" />Client *</label>
              <input type="text" name="clientName" value={formData.clientName} onChange={(e) => setFormData({...formData, clientName: e.target.value})} className="w-full px-4 py-3 bg-slate-700/50 border border-slate-600 rounded-lg text-white" placeholder="Nom du client" required />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2"><FileText className="w-4 h-4 inline mr-2" />Dossier</label>
              <input type="text" name="caseId" value={formData.caseId} onChange={(e) => setFormData({...formData, caseId: e.target.value})} className="w-full px-4 py-3 bg-slate-700/50 border border-slate-600 rounded-lg text-white" placeholder="ID du dossier associé" />
            </div>
          </div>

          {/* Sections de saisie - visibles seulement à l'écran */}
          <div className="space-y-6 print:hidden">
            <div className="space-y-4 p-4 border border-slate-700 rounded-lg">
              <h3 className="text-lg font-semibold text-indigo-400">Débours</h3>
              {renderCurrencyInput("Frais d'entrevue", "entrevue", formData.debours.entrevue, (e) => handleInputChange('debours', 'entrevue', e.target.value))}
              {renderCurrencyInput("Frais de dossier", "dossier", formData.debours.dossier, (e) => handleInputChange('debours', 'dossier', e.target.value))}
              {renderCurrencyInput("Frais de timbre de plaidoirie", "plaidoirie", formData.debours.plaidoirie, (e) => handleInputChange('debours', 'plaidoirie', e.target.value))}
              {renderCurrencyInput("Frais d'actes d'Huissier", "huissier", formData.debours.huissier, (e) => handleInputChange('debours', 'huissier', e.target.value))}
              {renderCurrencyInput("Frais de déplacement, de séjour et de vacation", "deplacement", formData.debours.deplacement, (e) => handleInputChange('debours', 'deplacement', e.target.value))}
            </div>

            <div className="space-y-4 p-4 border border-slate-700 rounded-lg">
              <h3 className="text-lg font-semibold text-purple-400">Honoraires</h3>
              {renderCurrencyInput("Forfait", "forfait", formData.honoraires.forfait, (e) => handleInputChange('honoraires', 'forfait', e.target.value))}
              {renderCurrencyInput("Taux horaire", "tauxHoraire", formData.honoraires.tauxHoraire, (e) => handleInputChange('honoraires', 'tauxHoraire', e.target.value))}
              {renderCurrencyInput("Honoraires de base", "base", formData.honoraires.base, (e) => handleInputChange('honoraires', 'base', e.target.value))}
              {renderCurrencyInput("Honoraires de résultat", "resultat", formData.honoraires.resultat, (e) => handleInputChange('honoraires', 'resultat', e.target.value))}
            </div>
          </div>

          {/* Tableau professionnel - visible à l'impression */}
          <div className="hidden print:block mb-8">
            <h3 className="text-lg font-semibold text-gray-800 mb-4">Détail des prestations</h3>
            <table className="w-full border-collapse border border-gray-300 text-sm">
              <thead>
                <tr className="bg-gray-100">
                  <th className="border border-gray-300 px-4 py-3 text-left font-semibold text-gray-800">Description</th>
                  <th className="border border-gray-300 px-4 py-3 text-center font-semibold text-gray-800">Quantité</th>
                  <th className="border border-gray-300 px-4 py-3 text-right font-semibold text-gray-800">Prix unitaire</th>
                  <th className="border border-gray-300 px-4 py-3 text-right font-semibold text-gray-800">Total</th>
                </tr>
              </thead>
              <tbody>
                {/* Débours */}
                {formData.debours.entrevue > 0 && (
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 text-gray-700">Frais d'entrevue</td>
                    <td className="border border-gray-300 px-4 py-2 text-center text-gray-700">1</td>
                    <td className="border border-gray-300 px-4 py-2 text-right text-gray-700">{formatCurrency(formData.debours.entrevue)} F CFA</td>
                    <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(formData.debours.entrevue)} F CFA</td>
                  </tr>
                )}
                {formData.debours.dossier > 0 && (
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 text-gray-700">Frais de dossier</td>
                    <td className="border border-gray-300 px-4 py-2 text-center text-gray-700">1</td>
                    <td className="border border-gray-300 px-4 py-2 text-right text-gray-700">{formatCurrency(formData.debours.dossier)} F CFA</td>
                    <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(formData.debours.dossier)} F CFA</td>
                  </tr>
                )}
                {formData.debours.plaidoirie > 0 && (
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 text-gray-700">Frais de timbre de plaidoirie</td>
                    <td className="border border-gray-300 px-4 py-2 text-center text-gray-700">1</td>
                    <td className="border border-gray-300 px-4 py-2 text-right text-gray-700">{formatCurrency(formData.debours.plaidoirie)} F CFA</td>
                    <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(formData.debours.plaidoirie)} F CFA</td>
                  </tr>
                )}
                {formData.debours.huissier > 0 && (
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 text-gray-700">Frais d'actes d'Huissier</td>
                    <td className="border border-gray-300 px-4 py-2 text-center text-gray-700">1</td>
                    <td className="border border-gray-300 px-4 py-2 text-right text-gray-700">{formatCurrency(formData.debours.huissier)} F CFA</td>
                    <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(formData.debours.huissier)} F CFA</td>
                  </tr>
                )}
                {formData.debours.deplacement > 0 && (
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 text-gray-700">Frais de déplacement, de séjour et de vacation</td>
                    <td className="border border-gray-300 px-4 py-2 text-center text-gray-700">1</td>
                    <td className="border border-gray-300 px-4 py-2 text-right text-gray-700">{formatCurrency(formData.debours.deplacement)} F CFA</td>
                    <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(formData.debours.deplacement)} F CFA</td>
                  </tr>
                )}
                
                {/* Honoraires */}
                {formData.honoraires.forfait > 0 && (
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 text-gray-700">Honoraires - Forfait</td>
                    <td className="border border-gray-300 px-4 py-2 text-center text-gray-700">1</td>
                    <td className="border border-gray-300 px-4 py-2 text-right text-gray-700">{formatCurrency(formData.honoraires.forfait)} F CFA</td>
                    <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(formData.honoraires.forfait)} F CFA</td>
                  </tr>
                )}
                {formData.honoraires.tauxHoraire > 0 && (
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 text-gray-700">Honoraires - Taux horaire</td>
                    <td className="border border-gray-300 px-4 py-2 text-center text-gray-700">1</td>
                    <td className="border border-gray-300 px-4 py-2 text-right text-gray-700">{formatCurrency(formData.honoraires.tauxHoraire)} F CFA</td>
                    <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(formData.honoraires.tauxHoraire)} F CFA</td>
                  </tr>
                )}
                {formData.honoraires.base > 0 && (
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 text-gray-700">Honoraires de base</td>
                    <td className="border border-gray-300 px-4 py-2 text-center text-gray-700">1</td>
                    <td className="border border-gray-300 px-4 py-2 text-right text-gray-700">{formatCurrency(formData.honoraires.base)} F CFA</td>
                    <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(formData.honoraires.base)} F CFA</td>
                  </tr>
                )}
                {formData.honoraires.resultat > 0 && (
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 text-gray-700">Honoraires de résultat</td>
                    <td className="border border-gray-300 px-4 py-2 text-center text-gray-700">1</td>
                    <td className="border border-gray-300 px-4 py-2 text-right text-gray-700">{formatCurrency(formData.honoraires.resultat)} F CFA</td>
                    <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(formData.honoraires.resultat)} F CFA</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {/* Résumé - visible à l'écran */}
          <div className="space-y-2 p-4 bg-slate-900/50 border border-slate-700 rounded-lg print:hidden">
            <h3 className="text-lg font-semibold text-white mb-4">Total</h3>
            <div className="flex justify-between text-slate-300"><p>Montant HT dû</p><p>{formatCurrency(totalHT)} F CFA</p></div>
            <div className="flex justify-between text-slate-300"><p>Montant TVA (18%)</p><p>{formatCurrency(tva)} F CFA</p></div>
            <div className="border-t border-slate-600 my-2"></div>
            <div className="flex justify-between text-white font-bold text-lg"><p>Total TTC</p><p>{formatCurrency(totalTTC)} F CFA</p></div>
            <p className="text-sm text-slate-400 italic capitalize">{numberToWords(totalTTC)} francs CFA</p>
          </div>

          {/* Totaux professionnel - visible à l'impression */}
          <div className="hidden print:block mb-8">
            <div className="flex justify-end">
              <div className="w-80">
                <table className="w-full border-collapse border border-gray-300 text-sm">
                  <thead className="sr-only">
                    <tr>
                      <th>Description</th>
                      <th>Montant</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="border border-gray-300 px-4 py-2 text-gray-700 font-semibold bg-gray-50">Sous-total HT:</td>
                      <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(totalHT)} F CFA</td>
                    </tr>
                    <tr>
                      <td className="border border-gray-300 px-4 py-2 text-gray-700 font-semibold bg-gray-50">TVA (18%):</td>
                      <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-gray-800">{formatCurrency(tva)} F CFA</td>
                    </tr>
                    <tr className="bg-gray-100">
                      <td className="border border-gray-300 px-4 py-3 text-gray-800 font-bold text-lg">TOTAL TTC:</td>
                      <td className="border border-gray-300 px-4 py-3 text-right font-bold text-lg text-gray-800">{formatCurrency(totalTTC)} F CFA</td>
                    </tr>
                  </tbody>
                </table>
                <div className="mt-2 text-sm text-gray-600 italic text-right">
                  Soit: {numberToWords(totalTTC)} francs CFA
                </div>
                {formData.payment.provision && (
                  <table className="w-full border-collapse border border-gray-300 text-sm mt-4">
                    <thead className="sr-only">
                      <tr>
                        <th>Description</th>
                        <th>Montant</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td className="border border-gray-300 px-4 py-2 text-gray-700 font-semibold bg-green-50">Provision versée:</td>
                        <td className="border border-gray-300 px-4 py-2 text-right font-semibold text-green-700">-{formatCurrency(formData.payment.provisionAmount)} F CFA</td>
                      </tr>
                      <tr className="bg-green-100">
                        <td className="border border-gray-300 px-4 py-3 text-green-800 font-bold">RESTE À PAYER:</td>
                        <td className="border border-gray-300 px-4 py-3 text-right font-bold text-green-800">{formatCurrency(resteAPayer)} F CFA</td>
                      </tr>
                    </tbody>
                  </table>
                )}
              </div>
            </div>
          </div>

          <div className="space-y-4 p-4 border border-slate-700 rounded-lg print:border-gray-300">
            <h3 className="text-lg font-semibold text-green-400 print:text-green-600">Paiement</h3>
            <div>
              <label htmlFor="payment-method" className="block text-sm font-medium text-slate-300 mb-2 print:text-black">Mode de paiement envisagé</label>
              <div id="payment-method" className="flex flex-wrap gap-4">
                {['Virement', 'Chèque', 'Carte bancaire', 'Espèces', 'Autre'].map(method => (
                  <label key={method} className="flex items-center text-slate-300 print:text-black">
                    <input type="radio" name="method" value={method.toLowerCase().replace(' ', '')} checked={formData.payment.method === method.toLowerCase().replace(' ', '')} onChange={handlePaymentChange} className="mr-2 h-4 w-4 text-indigo-600 focus:ring-indigo-500 print:hidden" />
                    {method}
                  </label>
                ))}
              </div>
            </div>
            <div>
              <label htmlFor="provision-section" className="block text-sm font-medium text-slate-300 mb-2 print:text-black">Dépôt de provision / Avance sur frais demandé(e)</label>
              <div id="provision-section" className="flex items-center gap-4">
                <label className="flex items-center text-slate-300 print:text-black">
                  <input type="radio" name="provision" value="true" checked={formData.payment.provision === true} onChange={handlePaymentChange} className="mr-2 h-4 w-4 text-indigo-600 focus:ring-indigo-500 print:hidden" />
                  {' '}Oui
                </label>
                <label className="flex items-center text-slate-300 print:text-black">
                  <input type="radio" name="provision" value="false" checked={formData.payment.provision === false} onChange={handlePaymentChange} className="mr-2 h-4 w-4 text-indigo-600 focus:ring-indigo-500 print:hidden" />
                  {' '}Non
                </label>
                {formData.payment.provision && (
                  <div className="relative flex-1">
                    <input type="text" name="provisionAmount" value={formatCurrency(formData.payment.provisionAmount)} onChange={handlePaymentChange} className="w-full pl-3 pr-14 py-2 bg-slate-700/50 border border-slate-600 rounded-lg text-white text-right print:bg-white print:text-black print:border-gray-300" placeholder="Montant" />
                     <span className="absolute inset-y-0 right-3 flex items-center text-slate-400 text-sm print:text-gray-500">F CFA</span>
                  </div>
                )}
              </div>
            </div>
            {formData.payment.provision && (
              <div className="mt-4 pt-4 border-t border-slate-700 print:border-gray-300">
                <div className="flex justify-between text-green-400 font-bold text-lg print:text-green-600">
                  <p>Reste à payer</p>
                  <p>{formatCurrency(resteAPayer)} F CFA</p>
                </div>
                <p className="text-sm text-slate-400 italic capitalize print:text-gray-600">{numberToWords(resteAPayer)} francs CFA</p>
              </div>
            )}
          </div>

          {/* Conditions de paiement - visible à l'impression */}
          <div className="hidden print:block mb-8">
            <div className="grid grid-cols-2 gap-8">
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-3">Conditions de paiement</h3>
                <div className="text-sm text-gray-700 space-y-2">
                  <p><strong>Mode de paiement:</strong> {getPaymentMethodLabel(formData.payment.method)}</p>
                  <p><strong>Échéance:</strong> À réception de facture</p>
                  <p><strong>Pénalités de retard:</strong> 3 fois le taux d'intérêt légal</p>
                  <p><strong>Indemnité forfaitaire:</strong> 40€ en cas de retard de paiement</p>
                </div>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-3">Informations légales</h3>
                <div className="text-xs text-gray-600 space-y-1">
                  <p>SIRET: 123 456 789 00012</p>
                  <p>N° TVA: FR12345678901</p>
                  <p>Code APE: 6910Z</p>
                  <p>Capital social: 10 000 €</p>
                  <p>RCS Paris B 123 456 789</p>
                </div>
              </div>
            </div>
          </div>

          {/* Zone de signature - visible à l'impression */}
          <div className="hidden print:block">
            <div className="flex justify-between mt-16">
              <div className="text-center">
                <p className="text-sm text-gray-700 mb-8">Le Client</p>
                <div className="border-t border-gray-300 w-48 mx-auto"></div>
                <p className="text-xs text-gray-500 mt-2">Signature et cachet</p>
              </div>
              <div className="text-center">
                <p className="text-sm text-gray-700 mb-8">Le Cabinet</p>
                <div className="border-t border-gray-300 w-48 mx-auto"></div>
                <p className="text-xs text-gray-500 mt-2">Signature</p>
              </div>
            </div>
          </div>

          {/* Boutons d'action - visibles seulement à l'écran */}
          <div className="flex gap-4 pt-6 print:hidden">
            <Button type="submit" className="flex-1 bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700">
              {invoice ? 'Mettre à jour' : 'Créer la Facture'}
            </Button>
            <Button type="button" variant="outline" onClick={onCancel} className="flex-1 border-slate-600 text-slate-300 hover:bg-slate-700">
              Annuler
            </Button>
          </div>
        </form>
      </motion.div>
    </motion.div>
  );
};

InvoiceForm.propTypes = {
  invoice: PropTypes.shape({
    invoiceNumber: PropTypes.string,
    clientName: PropTypes.string,
    caseId: PropTypes.string,
    debours: PropTypes.shape({
      entrevue: PropTypes.number,
      dossier: PropTypes.number,
      plaidoirie: PropTypes.number,
      huissier: PropTypes.number,
      deplacement: PropTypes.number
    }),
    honoraires: PropTypes.shape({
      forfait: PropTypes.number,
      tauxHoraire: PropTypes.number,
      base: PropTypes.number,
      resultat: PropTypes.number
    }),
    payment: PropTypes.shape({
      method: PropTypes.string,
      provision: PropTypes.bool,
      provisionAmount: PropTypes.number
    })
  }),
  onSubmit: PropTypes.func.isRequired,
  onCancel: PropTypes.func.isRequired,
  onPrint: PropTypes.func.isRequired,
  currentUser: PropTypes.shape({
    id: PropTypes.string,
    name: PropTypes.string
  }),
  existingInvoices: PropTypes.arrayOf(PropTypes.shape({
    invoiceNumber: PropTypes.string
  }))
};

export default InvoiceForm;